#### Load numpy library

In [3]:
import numpy as np

In [5]:
# 1) Basic

In [9]:
a = np.array([1,2,3,4,5])
print(type(a))
a

<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5])

In [24]:
b = np.array([[1,3,4,5,5], [3,5,6,6,8]])
print(type(b))
b

<class 'numpy.ndarray'>


array([[1, 3, 4, 5, 5],
       [3, 5, 6, 6, 8]])

In [16]:
# get dimentions
print('dimention of array a: ',a.ndim)
print('dimention of array b: ',b.ndim)

dimention of array a:  1
dimention of array b:  2


In [18]:
# get shape of the array
print(a.shape)
print(b.shape)

(5,)
(2, 5)


In [19]:
# get array type
print(a.dtype)
print(b.dtype)

int32
int32


In [21]:
## get size in bytes
print(a.itemsize)
print(b.itemsize)

4
4


In [23]:
## get total size in bytes
print(a.nbytes)  # a.size * a.itemsize
print(b.nbytes)  # b.size * b.itemsize

20
40


#### Acceesing elements of the arrray

In [28]:
a = np.array([[1,2,3,4,5,6,7], [11,12,13,14,15,16,17]])
print(a)

[[ 1  2  3  4  5  6  7]
 [11 12 13 14 15 16 17]]


In [30]:
# get specific element a[r, c]
a[1,3]

14

In [31]:
# get specific row a[r, :]
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [33]:
# get specific column a[:, c]
a[:, 1]

array([ 2, 12])

In [35]:
# get specific elements from rows and columns
a[0:2, 0:5] # get first 5 elements from each row

# another way
a[:, 0:5]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [40]:
# create all 0s element array
zeros = np.zeros((2,3), dtype='int32')
zeros

array([[0, 0, 0],
       [0, 0, 0]])

In [39]:
# crate all 1s element array
ones = np.ones((2,3), dtype='float32')
ones

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [46]:
## any number
all = np.full(shape=(2,3), fill_value=999)
print(all)

## crate array with same shape as another array but dirrente values
a_like = np.full_like(a , fill_value=77)
print(a_like)


[[999 999 999]
 [999 999 999]]
[[77 77 77 77 77 77 77]
 [77 77 77 77 77 77 77]]


In [53]:
## random
rand = np.random.rand(2, 3) ## random numbe between 0 and 1
print(rand)

np.random.randint(low=1, high=20, size=(2,3)) # get size (2,3) array with random number between 1 and 20.

[[0.07822792 0.17998188 0.98172609]
 [0.32745502 0.69154133 0.36895345]]


array([[ 5, 16, 10],
       [14, 10,  6]])

In [54]:
## identity matrix

i = np.identity(3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [61]:
## repeat an array 
arr1 = np.array([1,3,4])
print( np.repeat(arr1, 3, axis=0) )

arr2 = np.array([[1,2,3]])
print( np.repeat(arr2, 3, axis=0) )

[1 1 1 3 3 3 4 4 4]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [64]:
## carefull copying an array !

a = np.array([1,2,3])
b = a
b[0] = 9999
print(b) # change b
print(a) # changing b also chages a.

## use copy()
a = np.array([1,2,3])
b = a.copy()
b[0] = 9999
print(b) 
print(a) # changing b does not chage a.


[9999    2    3]
[9999    2    3]
[9999    2    3]
[1 2 3]
